(function(g){var window=this;'use strict';var Q3=function(a){a.ma("cardstatechange",a.Mi()&&a.Um()?1:0)},R3=function(a,b){var c=g.Ka(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},e7a=function(a){var b=g.Ol(a);
a=g.Rl(a);return new g.Dl(b.x,b.y,a.width,a.height)},f7a=function(a){return Math.pow(a,3)},g7a=function(a){return 3*a*a-2*a*a*a},U3=function(a){a=g.Pa(a);
delete S3[a];g.dd(S3)&&T3&&T3.stop()},i7a=function(){T3||(T3=new g.fo(function(){h7a()},20));
var a=T3;a.isActive()||a.start()},h7a=function(){var a=g.Ta();
g.Qc(S3,function(b){j7a(b,a)});
g.dd(S3)||i7a()},V3=function(a,b,c,d){g.Bo.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.T=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},j7a=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;k7a(a,a.progress);1==a.progress?(a.j=0,U3(a),a.onFinish(),a.AA()):a.Rc()&&a.kG()},k7a=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.T[c]-a.u[c])*b+a.u[c]},l7a=function(a,b){g.fb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},W3=function(a,b,c,d,e){V3.call(this,b,c,d,e);
this.element=a},m7a=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
W3.call(this,a,b,c,d,e)},n7a=function(a){g.C.call(this);
this.u=a||window;this.j=[]},X3=function(a){return a.baseUrl||null},Y3=function(a,b){return g.Bm(g.Tg(a,b),function(c){return!!c})},o7a=function(a,b,c){function d(S){var da=S.hovercardButton;
if(!da)return null;da=da.subscribeButtonRenderer;if(!da)return null;var P=f(da.unsubscribedButtonText),ra=f(da.subscribedButtonText);if(da.subscribed){var ea=f(da.subscriberCountWithUnsubscribeText);var qa=f(da.subscriberCountText)}else ea=f(da.subscriberCountText),qa=f(da.subscriberCountWithSubscribeText);var La=null;if(S.signinEndpoint){La=R3(S,"signinEndpoint","webNavigationEndpointData","url");if(!La){var ob,va;La=null==(va=g.O(null==(ob=da.signInEndpoint)?void 0:ob.commandMetadata,g.L2))?void 0:
va.url}if(!La)return null}return P&&(ra||La)?{subscribed:da.subscribed,subscribeText:P,subscribeCount:ea,unsubscribeText:ra,unsubscribeCount:qa,enabled:da.enabled,signinUrl:La,classic:S.useClassicSubscribeButton}:null}
function e(S){if(S){var da=[],P=S.videoId;P&&da.push("v="+P);(P=S.playlistId)&&da.push("list="+P);(S=S.startTimeSeconds)&&da.push("t="+S);return"/watch?"+da.join("&")}}
function f(S){if(!S)return null;var da=S.simpleText;return da?da:S.runs?g.Tg(S.runs,function(P){return P.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,w=null,y=null,z=!1,B=null,D=null,G=null,E=null,J=null,L=null;if("VIDEO"===h)g.O(l,g.dJ)?m=g.O(l,g.dJ).url:(L=g.O(l,g.fI),m=e(L)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.O(l,g.dJ)?m=g.O(l,g.dJ).url:(L=g.O(l,g.fI),m=e(L)),n=!1,q=a,w=f(b.playlistLength);else if("CHANNEL"===
h){if(z=R3(l,"browseEndpoint","browseId"))y=z,m="/channel/"+y;n=!1;q="new";(z=!!b.isSubscribe)?B=d(b):D=f(b.subscribersText)}else"WEBSITE"===h?((G=R3(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(E=f(b.productPrice)),b.additionalFeesText&&(J=f(b.additionalFeesText)),(n=R3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=R3(b,"title","accessibility","accessibilityData","label");var N=b.endpoint?b.endpoint.clickTrackingParams:null,
X="";if(b.metadata){var W=f(b.metadata);W&&(X=W)}return{id:"element-"+c,type:h,title:f(b.title),metadata:X,callToAction:f(b.callToAction),QP:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,isLiveVideo:p,playlistLength:w,channelId:y,subscribeButton:B,subscribersText:D,isSubscribe:z,targetUrl:m||null,D_:n,sessionData:N?{itct:N}:null,J4:q,Hy:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:Y3(b.impressionUrls||[],X3),s_:Y3(b.hovercardShowUrls||[],X3),clickUrls:Y3(l.loggingUrls||[],X3),visualElement:g.rA(b.trackingParams),productPrice:E,additionalFeesText:J,watchEndpoint:L||null}},p7a=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:Y3(a.impressionUrls||[],X3),elements:Y3(a.elements||[],function(d,e){return o7a(b,d,e)})};
a.trackingParams&&(c.visualElement=g.rA(a.trackingParams));return c},q7a=function(a){g.UP.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.Z=!0;this.I=0;a=a.V();this.T=g.hH(a)||"profilepage"===a.Ka;this.ea=a.experiments.gb("web_rounded_thumbnails");this.events=new g.gF(this);g.F(this,this.events);this.events.S(this.player,g.rB("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.sB("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.Bb);this.events.S(window,"focus",this.B3);this.load();var b=g.Ve("STYLE");(g.Ke("HEAD")[0]||
document.body).appendChild(b);g.eb(this,function(){g.af(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},r7a=function(a){return a.player.getVideoData().D?"current":a.T?"new":"current"},Z3=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},s7a=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=p7a(f,r7a(a))));$3(a,f)},
urlParams:{v:c},withCredentials:!0};a.T&&(c.urlParams.ptype="embedded");var d=b.Ru;d&&(c.postParams={ad_tracking:d});if(b=g.XDa(b))if(b=g.Zd(b),b=g.Xd(b))a.B=g.$u(b,c)},$3=function(a,b,c){c=void 0===c?!0:c;
a.player.Ef("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.t(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&t7a(a);c=[];d=new g.pB(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.V({F:"div",K:"ytp-ce-shadow"}),g.kP(a.player,a.u.element,4),a.C=new g.kN(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=u7a(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.kP(a.player,f.element,4);var h=new g.pB(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);v7a(a,
f,e)}else g.lA(new g.bw("buildEndscreenElement null",e))}a.player.ye(c);a.Bb()}},t7a=function(a){var b=g.uA(),c=g.vA();
c&&b&&a.endscreen.visualElement&&g.DL(c,b,a.endscreen.visualElement)},u7a=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={F:"div",Ga:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.Hy||"","aria-hidden":"true"},W:[{F:"div",K:"ytp-ce-element-shadow"},{F:"div",K:"ytp-ce-covering-image",X:a4(b)},{F:"div",K:"ytp-ce-covering-shadow-top"},{F:"a",K:"ytp-ce-covering-overlay",X:{href:b4(a,b.targetUrl),tabindex:"-1"},W:[{F:"div",Ga:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.Fo(b.title||"")},qa:b.title},{F:"div",K:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
qa:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={F:"div",Ga:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.Hy||"","aria-hidden":"true"},W:[{F:"div",K:"ytp-ce-element-shadow"},{F:"div",K:"ytp-ce-covering-image",X:a4(b)},{F:"div",K:"ytp-ce-covering-shadow-top"},{F:"a",K:"ytp-ce-covering-overlay",X:{href:b4(a,b.targetUrl),tabindex:"-1"},W:[{F:"div",Ga:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.Fo(b.title||"")},qa:b.title},{F:"div",K:"ytp-ce-playlist-count",
W:[{F:"div",K:"ytp-ce-playlist-icon"},{F:"div",K:"ytp-ce-playlist-count-text",qa:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={F:"div",Ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.Hy||"","aria-hidden":"true"},W:[{F:"div",K:"ytp-ce-element-shadow"},{F:"div",K:"ytp-ce-expanding-overlay",W:[{F:"div",K:"ytp-ce-expanding-overlay-hider"},{F:"div",K:"ytp-ce-expanding-overlay-background"},{F:"div",K:"ytp-ce-expanding-overlay-content",
W:[{F:"div",K:"ytp-ce-expanding-overlay-body",W:[{F:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{F:"a",Ga:["ytp-ce-channel-title","ytp-ce-link"],X:{href:b4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Fo(b.title||"")},qa:b.title},b.subscribeButton?{F:"div",K:"ytp-ce-subscribe-container",W:[{F:"div",K:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",K:"ytp-ce-channel-subscribers-text",qa:b.subscribersText}:"",b.metadata?{F:"div",Ga:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],qa:b.metadata}:""]}]}]}]},{F:"div",K:"ytp-ce-expanding-image",X:a4(b)}]};c=new g.V(c);var d=g.Le(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.no(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.XQ(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={F:"div",Ga:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.Hy||"","aria-hidden":"true"},W:[{F:"div",K:"ytp-ce-element-shadow"},{F:"div",K:"ytp-ce-expanding-overlay",W:[{F:"div",K:"ytp-ce-expanding-overlay-hider"},{F:"div",K:"ytp-ce-expanding-overlay-background"},{F:"div",K:"ytp-ce-expanding-overlay-content",
W:[{F:"div",K:"ytp-ce-expanding-overlay-body",W:[{F:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{F:"div",K:"ytp-ce-website-title",X:{dir:g.Fo(b.title||"")},qa:b.title},{F:"div",K:"ytp-ce-website-metadata",qa:b.metadata},{F:"a",Ga:["ytp-ce-website-goto","ytp-ce-link"],X:{href:b4(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{F:"div",K:"ytp-ce-expanding-image",X:a4(b)},{F:"div",K:"ytp-ce-expanding-icon",X:w7a(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={F:"div",K:"ytp-ce-merchandise-price-container",W:[{F:"div",K:"ytp-ce-merchandise-price",qa:b.productPrice}]},b.additionalFeesText&&c.W.push({F:"div",K:"ytp-ce-merchandise-additional-fees",qa:b.additionalFeesText})),a={F:"div",Ga:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.Hy||"","aria-hidden":"true"},W:[{F:"div",K:"ytp-ce-element-shadow"},{F:"div",K:"ytp-ce-expanding-overlay",W:[{F:"div",K:"ytp-ce-expanding-overlay-hider"},{F:"div",K:"ytp-ce-expanding-overlay-background"},
{F:"div",K:"ytp-ce-expanding-overlay-content",W:[{F:"div",K:"ytp-ce-expanding-overlay-body",W:[{F:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{F:"div",K:"ytp-ce-merchandise-title",X:{dir:g.Fo(b.title||"")},qa:b.title},c,{F:"div",K:"ytp-ce-merchandise-metadata",qa:b.metadata},{F:"a",Ga:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:b4(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{F:"div",K:"ytp-ce-expanding-image",X:a4(b)},{F:"div",K:"ytp-ce-merchandise-invideo-cta-container",
W:[{F:"div",K:"ytp-ce-merchandise-invideo-cta",qa:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.no(c.element,"ytp-ce-placeholder");return c},a4=function(a){if(a.QP)var b=a.QP.thumbnails;
return w7a(b?b[b.length-1].url:null)},w7a=function(a){return a?{style:"background-image: url("+a+")"}:{}},v7a=function(a,b,c){function d(m){m&&(b.Pa("blur",function(){"none"!=m.style.display&&a.Z&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.no(b.element,"ytp-ce-force-expand"),c4(a,c.id,!0)):(g.po(b.element,"ytp-ce-force-expand"),g.po(b.element,"ytp-ce-element-hover"),c4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Pa("mouseenter",function(){x7a(a,b,c)});
b.Pa("mouseleave",function(){y7a(a,b,c)});
a.player.V().isMobile||b.Pa("click",function(){g.no(b.element,"ytp-ce-element-hover")});
b.Pa("click",function(m){z7a(a,c,m)});
b.Pa("keypress",function(m){z7a(a,c,m)});
b.Pa("focus",function(){x7a(a,b,c)});
b.Pa("blur",function(){y7a(a,b,c)});
b.Pa("touchstart",function(){x7a(a,b,c)});
var l=g.Pe("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.po(b.element,"ytp-ce-element-hover");g.po(b.element,"ytp-ce-force-expand")});
b.Pa("keydown",function(m){a.Z=9===m.keyCode&&!m.shiftKey});
d(g.Pe("ytp-sb-subscribe",b.element));d(g.Pe("ytp-sb-unsubscribe",b.element));b.Pa("focus",f);b.Pa("blur",h)},z7a=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.mo(d,"ytp-ce-element");){g.mo(d,"subscribe-label")&&A7a(a,b);
if(g.mo(d,"ytp-ce-channel-subscribe"))return;d=g.bf(d)}if(!d||g.mo(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])y7a(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.J4)A7a(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Zd(b4(a,b.targetUrl)),g.MN(g.Xd(c),void 0,b.sessionData);else{var e=g.AH(a.player.V())||a.player.getVideoData().D,f=function(){var h=b4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.Mu(h);e&&n&&(n.v||
n.list)?a.player.qm(n.v,l,n.list,!1,void 0,m||void 0):g.LN(h,l)};
A7a(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},b4=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.IH(a)+b}else return"";return b},x7a=function(a,b,c){g.mo(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.no(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.fo(function(){g.no(b.element,"ytp-ce-element-hover")},200)).start():g.no(b.element,"ytp-ce-element-hover"),d4(a,c.s_),c4(a,c.id,!0))},y7a=function(a,b,c){g.po(b.element,"ytp-ce-element-hover");
g.po(b.element,"ytp-ce-force-expand");c4(a,c.id,!1)},c4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.t(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.ro(a.j[e].element,"ytp-ce-element-shadow-show",c)},d4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||Z3(a))c&&c();else{b=B7a(a,b);var e=0,f=!1,h=new g.fo(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.yx(b[a],d)}},A7a=function(a,b,c){d4(a,b.clickUrls,c);
(a=g.vA())&&b.D_&&g.HL(a,b.visualElement)},B7a=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(C7a(b[d],c));return a},C7a=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},D7a=function(a){return"string"===typeof a?a:""},e4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},E7a=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},f4=function(a){return a.value?a.value:null},g4=function(a){if(!a)return null;
var b=g.Zd(D7a(a.value));b=g.Xd(b);if(!b)return null;var c=e4(a.target,F7a,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new E7a(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},G7a=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},J7a=function(a){if(!a)return null;
var b=e4(a.type,H7a),c=e4(a.trigger,I7a);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=g4(a?a:null);return b?new G7a(b,c,a):null},K7a=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},L7a=function(a,b){return g.kb(a.action,b)},M7a=function(a,b){this.context=a;
this.j=b},N7a=function(a){return a.customMessage?h4("div","iv-card-message",a.customMessage):""},i4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{F:"div",K:"iv-card-image",X:{style:a},W:c}},O7a=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.t(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(h4("li","",c.value));return{F:"ul",K:"iv-card-meta-info",W:b}},h4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Fo(c);return{F:a,X:b,qa:c}},P7a=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Ry&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Ry+");");c.dir=g.Fo(a.customMessage);var d=[{F:"span",qa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",K:"iv-card-link-icon"}));return{F:"div",Ga:b,X:c,W:d}},j4=function(a,b,c,d){if(d){b=g.t(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Uh.click,5)}},Q7a=function(a,b){this.merchant=a;
this.price=b},R7a=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},S7a=function(a,b){return b?b:R7a(a)?"current":"new"},k4=function(a,b){g.C.call(this);
var c=this;this.element=a;this.context=b;this.qb=!1;this.Wa=new Map;this.Xa=new Map;this.context.G.addEventListener(g.rB("annotations_module"),function(d){(d=c.Wa.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.sB("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)})},l4=function(a,b,c,d,e,f,h){a.context.j.Pa(b,"click",function(l){a.lG(c,d,e,f||[],h||0,l)});
a.context.j.Pa(b,"touchstart",function(){a.qb=!1});
a.context.j.Pa(b,"touchmove",function(){a.qb=!0})},T7a=function(a){var b;
return(null==(b=g.O(a,g.dJ))?0:b.url)?g.O(a,g.dJ).url:(a=g.O(a,g.fI))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},m4=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
kU:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
uF:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},U7a=function(a,b,c){k4.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Oa=this.Tb=this.B=this.isInitialized=!1;this.Aa=null;this.cards=[];this.yb=this.T=this.Ma=this.D=this.Sa=this.j=null;this.ea=[];this.oa=this.J=this.Bf=this.Ka=null;this.I=0;this.Ba=new g.fo(function(){},c.Y.Uf?4E3:3E3);
g.F(this,this.Ba);this.kb=new g.fo(function(){});
g.F(this,this.kb);this.ya=new M7a(c,function(e,f,h,l,m,n){l4(d,e,f,h,l,m,n)});
this.Z=new g.V({F:"div",K:"iv-drawer",X:{id:"iv-drawer"},W:[{F:"div",K:"iv-drawer-header",X:{"aria-role":"heading"},W:[{F:"span",K:"iv-drawer-header-text"},{F:"button",Ga:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",K:"iv-drawer-content"}]});g.F(this,this.Z);this.C=this.Z.element;this.ib=new g.kN(this.Z,330);g.F(this,this.ib);this.Nb=g.Pe("iv-drawer-header-text",this.C);this.u=g.Pe("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Tb&&n4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Tb=d.B)&&o4(d)});
this.G.addEventListener("videodatachange",this.Mq.bind(this))},V7a=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){n4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){o4(a)});
var c=b.headerText;g.df(a.Nb,c);a.T&&a.T.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ka=g.rA(b.trackingParams);a.J=g.rA(b.closeTrackingParams);a.Bf=g.rA(b.iconTrackingParams)},W7a=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.G.V().experiments.gb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.wB(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Uh:{},Vm:null,Wj:e.trackingParams?g.rA(e.trackingParams):null,Bf:f&&f.trackingParams?g.rA(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
Ry:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};p4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.wB(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:q4(a,c,b,f),sponsored:!1,Uh:m4(f,e,f.command),Vm:f.trackingParams?g.rA(f.trackingParams):null,Wj:e.trackingParams?g.rA(e.trackingParams):null,Bf:l&&l.trackingParams?g.rA(l.trackingParams):null,imageUrl:r4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.wB(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,Ry:null,title:f.title?g.wB(f.title):"",customMessage:f.callToAction?g.wB(f.callToAction):"",url:g.O(f.command,g.dJ).url?g4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.O(f.command,g.dJ).url}):null,onClickCommand:null};p4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.wB(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:q4(a,c,b,e),sponsored:!1,Uh:m4(e,f,e.endpoint),Vm:e.trackingParams?g.rA(e.trackingParams):null,Wj:f.trackingParams?g.rA(f.trackingParams):null,Bf:l&&l.trackingParams?g.rA(l.trackingParams):null,channelId:g.O(e.endpoint,s4).browseId,customMessage:e.customText?g.wB(e.customText):null,profileImageUrl:r4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.wB(e.channelName):"",metaInfo:[e.subscriberCountText?g.wB(e.subscriberCountText):""],url:g4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.O(e.endpoint,s4).canonicalBaseUrl?g.O(e.endpoint,s4).canonicalBaseUrl:"/channel/"+g.O(e.endpoint,s4).browseId}),onClickCommand:null};p4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.wB(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:q4(a,c,b,e),sponsored:!1,Uh:m4(e,f,e.action),Vm:e.trackingParams?g.rA(e.trackingParams):null,Wj:f.trackingParams?g.rA(f.trackingParams):null,Bf:l&&l.trackingParams?g.rA(l.trackingParams):null,sB:r4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.wB(e.customMessage):null,playlistVideoCount:g.wB(e.playlistVideoCount),title:e.playlistTitle?g.wB(e.playlistTitle):"",metaInfo:[e.channelName?g.wB(e.channelName):
"",e.videoCountText?g.wB(e.videoCountText):""],url:g4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:T7a(e.action)}),onClickCommand:null};p4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.wB(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:q4(a,c,b,e),sponsored:!1,Uh:m4(e,f,e.action),Vm:e.trackingParams?g.rA(e.trackingParams):null,Wj:f.trackingParams?g.rA(f.trackingParams):null,Bf:l&&l.trackingParams?g.rA(l.trackingParams):null,sB:r4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.wB(e.lengthString):null,customMessage:e.customMessage?g.wB(e.customMessage):null,title:e.videoTitle?g.wB(e.videoTitle):"",metaInfo:[e.channelName?g.wB(e.channelName):
"",e.viewCountText?g.wB(e.viewCountText):""],isLiveNow:!!e.badge,url:g4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:T7a(e.action)}),onClickCommand:null};p4(a,b)}}}}}a.I++},r4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},q4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Y7a=function(a,b){if(b=X7a(a,b))b===a.j&&(a.j=null),a.G.removeCueRange(b.card.id),g.af(b.MH),g.sb(a.cards,b),a.tC(),t4(a)},n4=function(a,b,c){if(!a.B){a.ib.show();
a.Sa=new g.fo(function(){g.no(a.context.G.getRootNode(),g.lV.IV_DRAWER_OPEN)},0);
a.Sa.start();a.Aa=g.$x(a.u,"mousewheel",function(h){a.Ba.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.vA();d&&a.Ka&&a.J&&g.FL(d,[a.Ka,a.J]);b={TRIGGER_TYPE:b};for(var e=g.t(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.ER||(f.ER=!0,Z7a(a.context.logger,f.card.Uh.impression,b)),d&&g.FL(d,[f.card.Vm]);Q3(a.G);c&&(a.D=new g.fo(function(){a.Ma=a.T;a.yb.focus()},330),a.D.start())}},o4=function(a){a.B&&(a.ib.hide(),g.ay(a.Aa),a.Aa=null,g.po(a.context.G.getRootNode(),g.lV.IV_DRAWER_OPEN),a.B=!1,Q3(a.G),a.D&&a.D.stop(),a.D=new g.fo(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.D.start())},
a8a=function(a){g.oo(a.element,[g.lV.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.kP(a.G,a.C,5);$7a(a);a.T=g.Pe("ytp-cards-button",a.G.getRootNode());a.yb=g.Pe("iv-drawer-close-button",a.C);a.isInitialized=!0},$7a=function(a){var b=g.Pe("iv-drawer-close-button",a.C);
a.context.j.Pa(b,"click",a.ZY,a);a.context.j.Pa(a.u,"touchend",function(){a.Ba.start()});
a.context.j.Pa(a.u,"scroll",a.mZ,a);a.context.u.subscribe("onHideControls",function(){a.Oa=!0});
a.context.u.subscribe("onShowControls",function(){a.Oa=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Oa=g.mo(a.G.getRootNode(),"ytp-autohide")});
a.ea.push(g.ty("iv-button-shown",a.M_,a));a.ea.push(g.ty("iv-button-hidden",a.L_,a));a.ea.push(g.ty("iv-teaser-shown",a.LV,a));a.ea.push(g.ty("iv-teaser-hidden",a.N_,a));a.ea.push(g.ty("iv-teaser-clicked",a.KV,a))},b8a=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.O(b.onClickCommand,g.M3a))?void 0:c.targetId)?(a.oa=b,!0):!1},c8a=function(a,b){var c,d=null==(c=a.G.getVideoData())?void 0:c.multiMarkersPlayerBarRenderer;
if(null==d?0:d.markersMap){var e;for(c=0;(null==(e=d)?void 0:e.markersMap.length)>c;c++){var f=void 0,h=null==(f=d)?void 0:f.markersMap[c];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.O(h[0],g.FLa))?void 0:d.timeRangeStartMillis)||0,a.oa=null,!0}}a.oa=b;return!1},p4=function(a,b){if(!b8a(a,b)||c8a(a,b)){var c=d8a(a,b);
if(c){var d={card:b,MH:c.element,ER:!1};if(!b.onClickCommand){a.isInitialized||a8a(a);Y7a(a,b.id);var e=e8a(a,d);g.Cb(a.cards,e,0,d);c.Ca(a.u,e);a.tC()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,t4(a),f8a(a,d),n4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&g8a(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){g8a(a,d)}),t4(a))}}},d8a=function(a,b){switch(b.type){case "simple":var c=a.ya;
var d=b.displayDomain?{F:"div",K:"iv-card-image-text",qa:b.displayDomain}:void 0;var e=P7a(b);d={F:"div",Ga:["iv-card"],W:[{F:"a",K:"iv-click-target",X:{href:b.url?f4(b.url)||"":""},W:[i4(b.imageUrl,d),{F:"div",K:"iv-card-content",W:[h4("h2",void 0,b.title),e]}]}]};d=new g.V(d);j4(c,g.Oe("iv-click-target",d.element),b,b.url);b=d;break;case "collaborator":c=a.ya;d={F:"div",Ga:["iv-card","iv-card-channel"],W:[{F:"a",Ga:["iv-click-target"],X:{href:f4(b.url)||"","data-ytid":b.channelId},W:[i4(b.profileImageUrl),
{F:"div",K:"iv-card-content",W:[N7a(b),{F:"h2",K:"iv-card-primary-link",qa:b.title},O7a(b)]}]}]};d=new g.V(d);j4(c,g.Oe("iv-click-target",d.element),b,b.url);b=d;break;case "playlist":c=a.ya;d={F:"div",Ga:["iv-card","iv-card-playlist"],W:[{F:"a",K:"iv-click-target",X:{href:f4(b.url)||""},W:[i4(b.sB,{F:"div",K:"iv-card-image-overlay",W:[{F:"span",K:"iv-card-playlist-video-count",qa:b.playlistVideoCount}]}),{F:"div",K:"iv-card-content",W:[N7a(b),h4("h2","iv-card-primary-link",b.title),O7a(b)]}]}]};
d=new g.V(d);j4(c,g.Oe("iv-click-target",d.element),b,b.url);b=d;break;case "productListing":c=a.ya;var f=!g.qb(b.offers);d=["iv-card"];e="";var h=P7a(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({F:"div",K:"iv-card-offer-price",qa:h.price}),h.merchant&&f.push({F:"div",K:"iv-card-offer-merchant",qa:h.merchant}),h={F:"div",W:f});f=b.url?f4(b.url)||"":"";d={F:"div",Ga:d,X:{tabindex:"0"},W:[{F:"a",Ga:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{F:"div",K:"iv-card-content",W:[b.sponsored?{F:"div",K:"iv-card-sponsored",W:["Sponsored",{F:"div",K:"iv-ad-info-container",W:[{F:"div",K:"iv-ad-info",qa:"{{adInfo}}"},{F:"div",K:"iv-ad-info-icon-container",W:[{F:"div",K:"iv-ad-info-icon"},{F:"div",K:"iv-ad-info-callout"}]}]}]}:"",{F:"a",K:"iv-click-target",X:{href:f},W:[h4("h2",e,b.title),h]}]}]};d=new g.V(d);e=g.Ve("span");g.df(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Wd(e,"adInfo");j4(c,g.Oe("iv-click-target",d.element),b,b.url);b=d;break;case "video":c=a.ya;d=b.videoDuration?{F:"span",K:"iv-card-video-duration",qa:b.videoDuration}:void 0;e=b.isLiveNow?{F:"span",Ga:["yt-badge","yt-badge-live"],qa:"LIVE NOW"}:null;f={F:"div",Ga:["iv-card","iv-card-video"],W:[{F:"a",K:"iv-click-target",X:{href:(null==(h=b.url)?void 0:f4(h))||""},W:[i4(b.sB,d),{F:"div",K:"iv-card-content",W:[N7a(b),h4("h2","iv-card-primary-link",b.title),O7a(b),e]}]}]};d=new g.V(f);j4(c,g.Oe("iv-click-target",
d.element),b,b.url);b=d;break;default:return null}a.G.V().experiments.gb("web_rounded_containers")&&g.no(b.element,"ytp-rounded-info");return b},e8a=function(a,b){if(0===a.cards.length)return 0;
a=g.lb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},h8a=function(a){return a.j?"productListing"===a.j.card.type:g.Pk(a.cards,function(b){return"productListing"===b.card.type})},t4=function(a){g.ro(a.G.getRootNode(),"ytp-cards-shopping-active",h8a(a))},g8a=function(a,b){if(!g.mo(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.vA(),d=a.j?a.j.card.Bf:a.Bf;
c&&d&&g.GL(c,[d]);a.j=b;t4(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.G.qx(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.kb.isActive()||((!a.B||!a.Ba.isActive()&&a.Oa)&&f8a(a,b),a.kb.start(910+b.card.teaserDurationMs))}},f8a=function(a,b){a.Z.sb?(b=new V3([0,
a.u.scrollTop],[0,b.MH.offsetTop],600,g7a),a.context.B.Pa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Pa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.xM(a.Z,!0),a.u.scrollTop=b.MH.offsetTop,g.xM(a.Z,!1))},u4=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},X7a=function(a,b){return g.kb(a.cards,function(c){return c.card.id===b})},v4=function(a,b,c){k4.call(this,a,b);
this.annotation=c;this.isActive=!1},i8a=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},w4=function(a,b,c){v4.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},j8a=function(a,b){var c=void 0===c?0:c;
var d=e7a(b).width;g.Ml(b,d);c=new m7a(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,f7a);g.F(a,c);a.context.B.Pa(c,"begin",function(){g.Sl(b,!0)});
c.play()},m8a=function(a,b){if(b.channel_name){var c=a.createElement({F:"div",
Ga:["iv-branding-context-name"],qa:b.channel_name}),d=a.createElement({F:"div",Ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.XQ(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.j.Ca(d));var f=a.createElement({F:"div",Ga:["iv-branding-context-subscribe-caret"]}),h=a.createElement({F:"div",Ga:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Sl(h,!1);a.context.Y.N("web_rounded_containers")&&g.no(h,"ytp-rounded-branding-context");var l=a.createElement({F:"div",Ga:["branding-context-container-outer"]});l.appendChild(h);g.Gl(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.fo(function(){k8a(a,h,l)},500);
g.F(a,a.B);a.context.j.Pa(a.element,"mouseover",function(){l8a(a,h,l,f,b.image_height)});
a.context.j.Pa(a.element,"mouseout",function(){a.B.start()})}},l8a=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Rl(b);a.j||(b.style.width=g.Ll(f.width,!0),c.style.width=g.Ll(f.width,!0));g.Gl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Gl(d,"right","1px");a.C=!0;g.Sl(b,!0);a.D=new g.fo(function(){g.no(this.element,"iv-branding-active")},0,a);
a.D.start()}},k8a=function(a,b,c){g.po(a.element,"iv-branding-active");
a.I=new g.fo(function(){g.Sl(b,!1);a.j||(c.style.width=g.Ll(0,!0))},250);
a.I.start();a.C=!1},n8a=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.G=f;this.u=h},o8a=function(a,b,c){v4.call(this,a,b,c);
var d=this;this.T=this.isCollapsed=this.Z=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({F:"div",Ga:["iv-promo-contents"]});this.D=new g.fo(function(){d.j.setAttribute("aria-hidden","true");g.Sl(d.B,!1);g.Sl(d.u,!0)},700,this);
g.F(this,this.D)},q8a=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=a.annotation.Ge(),f=b.image_url;if(f){var h=a.createElement({F:"div",Ga:["iv-promo-img","iv-click-target"]});f=a.createElement({F:"img",X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({F:"span",K:"iv-promo-video-duration",qa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({F:"span",K:"iv-promo-playlist-length",qa:b.playlist_length.toString()}),h.appendChild(f));e&&l4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({F:"a",K:"iv-promo-txt"}),g.ke(f,f4(e)),a.j=f):a.j=a.createElement({F:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({F:"p",W:[{F:"strong",
qa:b.text_line_1}]});var m=a.createElement({F:"p",W:[{F:"span",K:"iv-promo-link",qa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({F:"button",Ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({F:"button",Ga:["iv-button","iv-promo-button"],W:[{F:"span",K:"iv-button-content",qa:f}]});var p=a.createElement({F:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&l4(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.no(a.j,
"iv-click-target");e&&l4(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({F:"p",W:[{F:"span",qa:b.text_line_1}]}),m=a.createElement({F:"p",W:[{F:"strong",qa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({F:"span",Ga:["yt-badge","iv-promo-badge-live"],qa:"LIVE NOW"})),g.no(a.j,"iv-click-target"),e&&l4(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);
p&&a.J.appendChild(p);c=a.createElement({F:"div",K:"iv-promo-actions"});a.u=a.createElement({F:"button",Ga:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Pa(a.u,"click",function(q){p8a(a,5E3,q)});
c.appendChild(a.u);g.Sl(a.u,!1);a.context.j.Pa(a.element,"mouseover",a.XZ,a);a.context.j.Pa(a.element,"mouseout",a.WZ,a);a.context.j.Pa(a.element,"touchend",function(q){p8a(a,5E3,q)});
a.B=a.createElement({F:"button",Ga:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Pa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.SZ:a.RZ,a);c.appendChild(a.B);g.oo(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},p8a=function(a,b,c){c.stopPropagation();
r8a(a);s8a(a,b);a.j.focus()},t8a=function(a){a.isCollapsed||a.T||a.C||(g.no(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},r8a=function(a){a.D.stop();
a.isCollapsed&&(g.qo(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Sl(a.u,!1),g.Sl(a.B,!0))},s8a=function(a,b){a.C||(a.C=g.Af(function(){u8a(this);
t8a(this)},b,a))},u8a=function(a){a.C&&(g.Ca.clearTimeout(a.C),a.C=null)},v8a=function(a){this.G=a},Z7a=function(a,b,c){b&&(c?x4(a,b.map(function(d){return g.Yn(d,c)})):x4(a,b))},x4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.t(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.yx(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},w8a=function(a){g.UP.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new v8a(this.player);this.D=new g.gF(this);this.C=this.Yn=null;this.events=new g.gF(this);this.J=this.j=null;this.T=[];g.F(this,this.D);this.D.S(this.player,"onVideoAreaChange",function(){b.ma("onVideoAreaChange")});
this.D.S(this.player,"onHideControls",function(){b.ma("onHideControls")});
this.D.S(this.player,"onShowControls",function(){b.ma("onShowControls")});
this.D.S(this.player,"resize",function(d){b.ma("resize",d)});
this.D.S(this.player,"presentingplayerstatechange",function(d){b.ma("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.MV,this);this.subscribe("resize",this.vE,this);this.player.V().oa.subscribe("vast_info_card_add",this.QS,this);g.F(this,this.events);this.Z=this.createElement({F:"div",K:"video-custom-annotations"});this.u=new g.V({F:"div",Ga:["ytp-player-content","ytp-iv-player-content"]});g.F(this,this.u);g.kP(this.player,this.u.element,4);this.u.hide();this.B=new g.V({F:"div",Ga:["ytp-iv-video-content"]});g.F(this,this.B);a=this.createElement({F:"div",K:"video-annotations"});
a.appendChild(this.Z);this.B.element.appendChild(a);this.uu()&&this.load();var c=this.createElement({F:"style"});(g.Ke("HEAD")[0]||document.body).appendChild(c);g.eb(this,function(){g.af(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},x8a=function(a){a=a.createElement({F:"div",
Ga:["annotation","annotation-type-custom"]});g.Sl(a,!1);return a},y8a=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.xM(a.u,b);g.xM(a.B,b)},z8a=function(a,b){for(var c={},d=g.t(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ma(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(z8a(a,e))}return c},D8a=function(a){var b=a.player.getVideoData();
if(b.Wa){var c=a.player.V().oa.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Uu(h)&&h.responseXML?h.responseXML:null)&&A8a(a,h)}};
g.$v()&&(d.onFinish=B8a(a,d.onFinish));d.postParams={ic_only:"1"};C8a(d,c);g.$u(b.Wa,d)}}},C8a=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Uy&&(a.postParams.ic_coll=b.Uy);b.zC&&(a.postParams.ic_xml=b.zC);b.vB&&(a.postParams.ic_track=b.vB)},E8a=function(a){var b=new g.V({F:"div"});
g.Sl(b.element,!1);var c=new U7a(a.player,b.element,y4(a));g.F(c,b);b.Ca(a.u.element);c.hB();return c},y4=function(a){if(!a.J){var b=new n7a(a);
g.F(a,b);var c=new g.Mj(a);g.F(a,c);a.J=new n8a(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.hh)}return a.J},A8a=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)){var e=d[0].getAttribute("itct");if(e&&(d=g.vA())){var f=g.uA();f&&(e=[g.rA(e)],g.Au("safe_logging_library_killswitch")?g.yA(void 0,d,f,e):g.Gu(g.yA)(void 0,d,f,e))}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){e=z8a(a,b[d]);f=null;try{if(e){var h=e.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=e4(e.type,F8a),p=e4(e.style,G8a),q=D7a(e.data),r=0!==q.length?JSON.parse(q):{};var w=e.action;e=J7a;if(null==w)var y=null;else if(g.Ka(w)){l=
[];for(var z=g.t(w),B=z.next();!B.done;B=z.next()){var D=e(B.value);D&&l.push(D)}y=l}else{var G=e(w);y=G?[G]:[]}f=m&&n?new K7a(m,n,p,y,r):null}else f=null}catch(W){}if(f)if("branding"===f.type||"promotion"===f.type){e=a;l=f;var E=x8a(e),J=null;switch(l.type){case "branding":if(e.player.V().pd)break;e.u.element.appendChild(E);J=new w4(E,y4(e),l);break;case "promotion":g.kP(e.player,E,4),J=new o8a(E,y4(e),l)}J&&J.hB();if(e=J)g.F(a,e),a.I[f.id]=e}else if("card"===f.type||"drawer"===f.type){a.j||(a.j=
E8a(a),g.F(a,a.j));if("card"===f.type){c=a.j;var L=f&&f.data&&f.data.card_type;e=f.data;if(L)switch(l=e.tracking||{},l={impression:l.impression,click:l.click,close:l.close,kU:l.teaser_impression,uF:l.teaser_click},E=e.tracking_params||{},J=null,L){case "collaborator":f={id:f.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Uh:l,Vm:E.card?g.rA(E.card):
null,Wj:E.teaser?g.rA(E.teaser):null,Bf:E.icon?g.rA(E.icon):null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:g4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};p4(c,f);break;case "playlist":f={id:f.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,
sessionData:e.session_data||{},sponsored:e.sponsored||!1,Uh:l,Vm:E.card?g.rA(E.card):null,Wj:E.teaser?g.rA(E.teaser):null,Bf:E.icon?g.rA(E.icon):null,sB:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:g4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};p4(c,f);break;case "productListing":e.signin_url&&(J=g4({target:"current",value:e.signin_url}));L=
[];for(var N=e.offers||[],X=0;X<N.length;X++)L.push(new Q7a(g.Ee(N[X].merchant),g.Ee(N[X].price)));f={id:f.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Uh:l,Vm:E.card?g.rA(E.card):null,Wj:E.teaser?g.rA(E.teaser):null,Bf:E.icon?g.rA(E.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,
Ry:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:g4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),f8a:J,e8a:e.signin_title?e.signin_title:void 0,d8a:e.signin_message?e.signin_message:void 0,offers:L,onClickCommand:null};p4(c,f);break;case "simple":f={id:f.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||
!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Uh:l,Vm:E.card?g.rA(E.card):null,Wj:E.teaser?g.rA(E.teaser):null,Bf:E.icon?g.rA(E.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,Ry:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:g4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};p4(c,f);break;case "video":f=
{id:f.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Uh:l,Vm:E.card?g.rA(E.card):null,Wj:E.teaser?g.rA(E.teaser):null,Bf:E.icon?g.rA(E.icon):null,sB:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:g4({pause_on_navigation:e.pause_on_navigation,
target:e.target||"new",value:e.url}),onClickCommand:null},p4(c,f)}}else V7a(a.j,f);c=!0}}c&&(Q3(a.player),a.vE())},H8a=function(a,b){var c=!1;
a.j||(a.j=E8a(a),g.F(a,a.j));for(var d=g.t(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(W7a(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.wB(b.headerText):"",g.df(c.Nb,d),c.T&&c.T.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ka=b.trackingParams?g.rA(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.rA(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Bf=b.icon.infoCardIconRenderer.trackingParams?
g.rA(b.icon.infoCardIconRenderer.trackingParams):null,Q3(a.player),a.vE())},I8a=function(a,b,c,d,e){if(!a.player.V().pd){var f=[];
b.navigationEndpoint&&g.O(b.navigationEndpoint,s4)&&g.O(b.navigationEndpoint,s4).browseId&&f.push(new G7a("openUrl","click",new E7a("/channel/"+g.O(b.navigationEndpoint,s4).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.O(b.subscribeButton,
g.tJ)){d.channel_id=g.O(b.subscribeButton,g.tJ).channelId;var l;b=g.O(b.subscribeButton,g.tJ);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.wB(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.wB(b.subscriberCountText))):(b.subscriberCountText&&(e=g.wB(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.wB(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.O(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.L2))?void 0:m.url)||"";l={subscribeText:g.wB(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.wB(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new K7a(c,"branding","branding",f,d);l=x8a(a);a.u.element.appendChild(l);f=new w4(l,y4(a),f);f.hB();g.F(f,f);a.I[c]=f}},B8a=function(a,b){return function(){var c=g.xa.apply(0,arguments);
a.isDisposed()||a.T.push(g.ao.Gh(function(){b.apply(null,g.u(c))}))}},J8a=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.dP.prototype.qx=g.ba(19,function(a,b){var c=g.lQ(this.vb());c&&c.qx(a,b)});
var S3={},T3=null;g.Ua(V3,g.Bo);g.k=V3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Rc())return!1;U3(this);this.startTime=a=g.Ta();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.rE();this.Ak("play");-1==this.j&&this.Ak("resume");this.j=1;var b=g.Pa(this);b in S3||(S3[b]=this);i7a();j7a(this,a);return!0};
g.k.stop=function(a){U3(this);this.j=0;a&&(this.progress=1);k7a(this,this.progress);this.Ak("stop");this.AA()};
g.k.pause=function(){this.Rc()&&(U3(this),this.j=-1,this.Ak("pause"))};
g.k.ra=function(){0==this.j||this.stop(!1);this.Ak("destroy");V3.hf.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.kG=function(){this.Ak("animate")};
g.k.Ak=function(a){this.dispatchEvent(new l7a(a,this))};
g.Ua(l7a,g.fb);g.Ua(W3,V3);W3.prototype.C=function(){};
W3.prototype.kG=function(){this.C();W3.hf.kG.call(this)};
W3.prototype.AA=function(){this.C();W3.hf.AA.call(this)};
W3.prototype.rE=function(){this.C();W3.hf.rE.call(this)};
g.Ua(m7a,W3);m7a.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var s4=new g.fp("browseEndpoint");g.v(n7a,g.C);g.k=n7a.prototype;g.k.Pa=function(a,b,c,d){c=(0,g.Qa)(c,d||this.u);a=g.$x(a,b,c);this.j.push(a);return a};
g.k.YD=function(a,b,c,d){c=(0,g.Qa)(c,d||this.u);a=g.Xoa(a,b,c);this.j.push(a);return a};
g.k.Ac=function(a){g.ay(a);g.sb(this.j,a)};
g.k.cg=function(){g.ay(this.j);this.j.length=0};
g.k.ra=function(){this.cg();g.C.prototype.ra.call(this)};g.v(q7a,g.UP);g.k=q7a.prototype;g.k.load=function(){g.UP.prototype.load.call(this);if(!Z3(this)){var a=g.YDa(this.player.getVideoData());a?(a=p7a(a,r7a(this)),$3(this,a,!1)):s7a(this)}};
g.k.unload=function(){$3(this,null);this.B&&(this.B.abort(),this.B=null);g.UP.prototype.unload.call(this)};
g.k.Sg=function(a,b){return Z3(this)?"loadCustomEndscreenRenderer"===a?(a=p7a(b,"new"),$3(this,a),!0):null:null};
g.k.getOptions=function(){return Z3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Bb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<K8a.length;f++){var h=Math.abs(b.width-K8a[f]);if(-1===e||d>=h)e=f,d=h}d=L8a[e];this.u&&g.Gl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Ql(e.element,m,f);g.Ml(e.element,n,p);this.ea&&(g.qo(e.element,M8a),256<m||256<f?g.no(e.element,"ytp-ce-large-round"):96<m||96<f?g.no(e.element,"ytp-ce-medium-round"):g.no(e.element,"ytp-ce-small-round"));g.qo(e.element,N8a);m=h.left+h.width/2;h=h.top+l/2;g.no(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.qo(e.element,L8a);g.no(e.element,d);(e=g.Le(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Gl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())d4(this,this.endscreen.impressionUrls),(a=g.vA())&&this.endscreen.visualElement&&g.EL(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.no(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.no(b,"ytp-ce-shown");d4(this,c.impressionUrls);(b=g.vA())&&g.EL(b,c.visualElement);this.player.V().D&&this.player.Qa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.po(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.po(b,"ytp-ce-shown");this.player.V().D&&this.player.Qa("endscreenelementhidden",a)}};
g.k.B3=function(a){var b=this;a.target===window&&(new g.fo(function(){for(var c=g.t(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.qo(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var K8a=[346,426,470,506,570,640,853,1280,1920],L8a="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),N8a=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],M8a=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var F7a={zla:"current",pIa:"new"};var H7a={CLOSE:"close",TLa:"openUrl",SUBSCRIBE:"subscribe"},I7a={Ega:"click",CLOSE:"close",fva:"hidden",lRa:"rollOut",mRa:"rollOver",pTa:"shown"};K7a.prototype.Ge=function(){var a=L7a(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var G8a={jca:"anchored",mV:"branding",CHANNEL:"channel",ola:"cta",iva:"highlightText",Rya:"label",PLAYLIST:"playlist",LOa:"popup",PVa:"speech",SUBSCRIBE:"subscribe",VYa:"title",VIDEO:"video",u4a:"website"},F8a={mV:"branding",Fea:"card",Bna:"drawer",hva:"highlight",BEa:"marker",NPa:"promotion",TEXT:"text",g5a:"widget"};g.v(k4,g.C);g.k=k4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.pB(a,b,{id:c,namespace:"annotations_module"});d&&this.Wa.set(a,d);e&&this.Xa.set(a,e);this.context.G.ye([a])};
g.k.hB=function(){this.context.u.subscribe("resize",this.tC,this)};
g.k.lG=function(a,b,c,d,e,f){if(this.qb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.af(this.element)};
g.k.tC=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=f4(a);if(f){var h=S7a(f,a.target),l=function(){a.j&&e.context.G.pauseVideo();var m=e.context.videoData.D||!1,n=g.Mu(f||"");m&&n&&(n.v||n.list)?e.context.G.qm(n.v,b,n.list,!1):g.MN(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);x4(this.context.logger,c,l,d);R7a(f)||(c=g.vA(),d=b.itct,c&&d&&g.HL(c,g.rA(d)))}};
g.k.ra=function(){this.Wa.clear();this.Xa.clear();g.C.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.F(this,a);return a.element};g.v(U7a,k4);g.k=U7a.prototype;g.k.Mq=function(){this.oa&&p4(this,this.oa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Rl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.tC=function(){var a=this.isAvailable();g.Sl(this.element,a);g.ro(this.context.G.getRootNode(),g.lV.IV_DRAWER_ENABLED,a);Q3(this.G)};
g.k.destroy=function(){this.G.qx(!1);try{this.G.getRootNode().removeChild(this.C)}catch(a){}g.uy(this.ea);g.ay(this.Aa);this.Sa&&this.Sa.dispose();this.D&&this.D.dispose();k4.prototype.destroy.call(this)};
g.k.ZY=function(){if(this.B){x4(this.context.logger,u4(this).Uh.close);var a=g.vA();a&&this.J&&g.HL(a,this.J);o4(this)}};
g.k.mZ=function(){g.ro(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.M_=function(){var a=g.vA(),b=u4(this);b=b?b.Bf:this.Bf;a&&b&&g.FL(a,[b])};
g.k.L_=function(){var a=g.vA(),b=u4(this);b=b?b.Bf:this.Bf;a&&b&&g.GL(a,[b])};
g.k.LV=function(){var a=u4(this);x4(this.context.logger,a.Uh.kU);var b=g.vA();b&&a&&g.FL(b,[a.Wj,a.Bf])};
g.k.N_=function(){var a=g.vA(),b=u4(this);a&&b&&g.GL(a,[b.Wj])};
g.k.KV=function(a){var b=u4(this),c=g.vA();this.j?a?(a=this.context.logger,x4(a,b.Uh.uF),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Wj&&g.HL(c,b.Wj)):(a=this.context.logger,x4(a,b.Uh.uF),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Bf&&g.HL(c,b.Bf)):(a=this.context.logger,x4(a,b.Uh.uF),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.Bf&&g.HL(c,this.Bf))};g.v(v4,k4);v4.prototype.hB=function(){k4.prototype.hB.call(this);i8a(this)};
v4.prototype.show=function(){k4.prototype.show.call(this);var a=g.vA(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.FL(a,[g.rA(b.itct)])};
v4.prototype.hide=function(){k4.prototype.hide.call(this);var a=g.vA(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.GL(a,[g.rA(b.itct)])};g.v(w4,v4);
w4.prototype.show=function(){if(!this.isActive){v4.prototype.show.call(this);if(!this.J){g.no(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({F:"img",Ga:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Sl(this.u,!1);var b=this.createElement({F:"button",Ga:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=this.annotation.Ge();c&&l4(this,
b,c,this.annotation.id,a.session_data);m8a(this,a);this.J=!0}g.Sl(this.element,!0);this.isActive=!0;this.u&&(j8a(this,this.u),g.no(this.context.G.getRootNode(),"ytp-branding-shown"))}};
w4.prototype.hide=function(){this.isActive&&(v4.prototype.hide.call(this),g.Sl(this.element,!1),this.isActive=!1,g.po(this.context.G.getRootNode(),"ytp-branding-shown"))};
w4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);v4.prototype.destroy.call(this)};g.v(o8a,v4);g.k=o8a.prototype;g.k.show=function(){this.isActive||(v4.prototype.show.call(this),this.Z||(q8a(this),this.Z=!0),g.Sl(this.element,!0),g.Af(function(){g.po(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,u8a(this),r8a(this),s8a(this,this.I))};
g.k.hide=function(){this.isActive&&(g.no(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.lG=function(a,b,c,d,e,f){return this.isCollapsed?!1:v4.prototype.lG.call(this,a,b,c,d,e,f)};
g.k.XZ=function(a){this.T=!0;p8a(this,500,a)};
g.k.WZ=function(){this.T=!1;t8a(this)};
g.k.RZ=function(a){a.stopPropagation();this.hide()};
g.k.SZ=function(a){a.stopPropagation();u8a(this);this.isCollapsed=!0;g.no(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();v4.prototype.destroy.call(this)};g.v(w8a,g.UP);g.k=w8a.prototype;g.k.Sg=function(a,b){if(!J8a(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.j2a(b))&&A8a(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Y7a(this.j,b),Q3(this.player)),!0}return null};
g.k.getOptions=function(){return J8a(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.uu=function(){var a=this.player.V(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.nN||a.oa.get(b.videoId)||g.AJ(b)||g.BJ(b)?!0:!1};
g.k.vE=function(){if(this.B){var a=this.player.fb().getVideoContentRect(!0);g.Ql(this.B.element,a.width,a.height);g.Ml(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Bj();a=this.j;b=b.width;g.ro(a.C,"iv-drawer-small",426>=b);g.ro(a.C,"iv-drawer-big",1280<=b)}};
g.k.MV=function(a){y8a(this,a.state);g.U(a.state,2)&&(this.Mi()&&this.Um()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.qx(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Uu(h)&&h.responseXML?h.responseXML:null)&&(A8a(b,h),g.no(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.UP.prototype.load.call(this);y8a(this,this.player.Eb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.$v()&&(a=B8a(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().oa.get(d);f&&C8a(e,f);f=f&&(f.zC||f.Uy);if(!c.Ku||f)c.Wa?this.C=g.$u(c.Wa,e):(this.Yn=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Yn));
g.kP(this.player,this.B.element,4);this.vE();(f=g.AJ(c))&&H8a(this,f);(f=g.BJ(c))&&f.featuredChannel&&I8a(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Wa&&(this.Yn&&(this.player.removeEventListener("videodatachange",this.Yn),this.Yn=null),this.C=g.$u(b.Wa,a))};
g.k.unload=function(){this.player.Ef("annotations_module");for(var a=g.t(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,Q3(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.UP.prototype.unload.call(this);this.B.detach();this.Yn&&(this.player.removeEventListener("videodatachange",this.Yn),this.Yn=null)};
g.k.QS=function(a){a===this.player.getVideoData().videoId&&(this.loaded?D8a(this):this.load())};
g.k.Mi=function(){return!!this.j&&this.j.isAvailable()};
g.k.Um=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Mi();this.j&&(a?c?n4(this.j,c,b):n4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):o4(this.j))};
g.k.qx=function(a,b){this.player.ma(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.V().oa.unsubscribe("vast_info_card_add",this.QS,this);g.po(this.player.getRootNode(),g.lV.IV_DRAWER_OPEN);for(var a=this.T,b=g.ao,c=0,d=a.length;c<d;c++)b.Al(a[c]);this.T.length=0;g.UP.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.F(this,a);return a.element};g.TP("annotations_module",w8a);g.TP("creatorendscreen",q7a);})(_yt_player);
