(function(g){var window=this;'use strict';var Y$a=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.K2a)("0",Math.max(0,b-c))+a},Z$a=function(){return{F:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},W:[{F:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},$$a=function(){return{F:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},W:[{F:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},bab=function(a){"number"===typeof a?(this.date=aab(a,0,1),z6(this,1)):g.Ma(a)?(this.date=aab(a.getFullYear(),a.getMonth(),a.getDate()),z6(this,a.getDate())):(this.date=new Date(g.Ta()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),z6(this,a))},aab=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},z6=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},A6=function(a,b){g.mP.call(this,a,{F:"div",
K:"ytp-reminder-menu",X:{role:"menu",tabindex:"-1"},W:[{F:"div",K:"ytp-reminder-menu-contents",W:[{F:"div",K:"ytp-reminder-menu-items"}]}]},100,!0);this.buttonElement=b;this.j=[];this.menuPopupRenderer=void 0;this.items=this.Da("ytp-reminder-menu-items");this.hide()},dab=function(a){var b=cab(a),c=0,d={};
for(c=0;c<b.length;d={KF:d.KF},c++){var e=a.j[c];e||(e=new g.V({F:"div",K:"ytp-reminder-menu-item",X:{role:"menuitem",tabindex:"0"},W:[{F:"div",K:"ytp-reminder-menu-item-icon",qa:"{{icon}}"},{F:"div",K:"ytp-reminder-menu-item-label",qa:"{{text}}"}]}),d.KF=c,e.Pa("click",function(l){return function(){var m=l.KF;a.wb();m=cab(a)[m];a.ma("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.Ca(a.items),a.j[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=Z$a();break;case "NOTIFICATIONS_NONE":h=$$a();break;case "NOTIFICATIONS_ACTIVE":h=g.IM()}f=f.text?g.wB(f.text):"";e.update({icon:h,text:f})}for(;c<a.j.length;)a.j.pop().dispose();0===c?a.wb():a.Lc(a.buttonElement)},cab=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},B6=function(a){g.V.call(this,{F:"div",
W:[{F:"button",Ga:["ytp-offline-slate-button","ytp-button"],W:[{F:"div",K:"ytp-offline-slate-button-icon",qa:"{{icon}}"},{F:"div",K:"ytp-offline-slate-button-text",qa:"{{text}}"}]}]});this.G=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.u=void 0;this.C=this.j=null;(this.buttonElement=this.Da("ytp-offline-slate-button"))&&this.S(this.buttonElement,"click",this.D);this.hide()},fab=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=
b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&g.O(c,eab)?a.upcomingEventReminderButtonRenderer=g.O(c,eab):c&&g.O(c,eab)||(a.upcomingEventReminderButtonRenderer=null);C6(a)},C6=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.wB(b.toggledText):"";a.update({text:c,icon:gab(b.toggledIcon)})}else c=b.defaultText?g.wB(b.defaultText):"",a.update({text:c,icon:gab(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=hab(a))?(c=b.text?g.wB(b.text):"",a.update({text:c,icon:gab(b.icon)}),a.show()):a.hide():a.hide()},jab=function(a,b,c){a.C||(a.C=new g.Jx(a.G.V().Ri));
var d={context:g.kx(a.C.config_||g.jx())};g.vA()&&(d.context.clientScreenNonce=g.vA());d.params=c;g.Kx(a.C,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.u&&(a.upcomingEventReminderButtonRenderer.currentState=a.u,a.u=void 0)},
onError:function(){iab(a)},
onTimeout:function(){iab(a)}})},iab=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,C6(a)):a.upcomingEventReminderButtonRenderer&&(a.u=void 0,C6(a))},gab=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return Z$a();case "NOTIFICATIONS_NONE":return $$a();case "NOTIFICATIONS_ACTIVE":return g.IM();default:return null}},hab=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.u||a.upcomingEventReminderButtonRenderer.currentState;a=g.t(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=g.O(c.value,kab))&&c.state===b&&c.button&&g.O(c.button,g.cJ))return g.O(c.button,g.cJ);return null},lab=function(a){g.V.call(this,{F:"div",
K:"ytp-offline-slate",W:[{F:"div",K:"ytp-offline-slate-background"},{F:"div",K:"ytp-offline-slate-bar",W:[{F:"span",K:"ytp-offline-slate-icon",W:[{F:"svg",X:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},W:[{F:"path",X:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{F:"circle",X:{cx:"12",cy:"12",r:"3"}}]}]},{F:"span",K:"ytp-offline-slate-messages",W:[{F:"div",K:"ytp-offline-slate-main-text",X:{"aria-label":"{{label}}"},qa:"{{mainText}}"},{F:"div",K:"ytp-offline-slate-subtitle-text",qa:"{{subtitleText}}"}]},{F:"span",K:"ytp-offline-slate-buttons"}]},{F:"button",Ga:["ytp-offline-slate-close-button","ytp-button"],W:[g.DM()]},{F:"button",Ga:["ytp-offline-slate-open-button","ytp-button"],W:[g.CM()]}]});var b=this;this.api=a;this.j=this.u=null;this.background=this.Da("ytp-offline-slate-background");
this.B=this.Da("ytp-offline-slate-bar");this.D=new g.fo(function(){g.no(b.B,"ytp-offline-slate-bar-fade")},15E3);
this.I=!1;this.C=new g.fo(function(){g.no(b.element,"ytp-offline-slate-collapsed")},15E3);
g.F(this,this.C);g.F(this,this.D);this.countdownTimer=new g.fo(this.IU,1E3,this);this.S(a,"presentingplayerstatechange",this.MU);this.S(a,"livestatedata",this.La);var c=this.Da("ytp-offline-slate-close-button");this.S(c,"click",function(){g.no(b.element,"ytp-offline-slate-collapsed")});
c=this.Da("ytp-offline-slate-open-button");this.S(c,"click",function(){g.po(b.element,"ytp-offline-slate-collapsed")});
this.hide();c=this.getVideoData();c.getPlayerResponse()&&(c=c.getPlayerResponse().playabilityStatus)&&this.La(c);c=8===this.api.getPresentingPlayerType()&&!this.getVideoData().jk;var d=8===this.api.getPresentingPlayerType();g.ro(this.element,"ytp-offline-slate-premiere-trailer",c);g.ro(this.element,"ytp-offline-slate-hide-background",d);a.N("web_rounded_containers")&&g.no(this.B,"ytp-rounded-offline-slate")},mab=function(a,b,c){if(b){var d=null!=b.subtitleText?g.wB(b.subtitleText):"";
c=c?c:null!=b.mainText?g.wB(b.mainText):"";var e,f,h,l;b=null!=(l=null==(e=b.mainText)?void 0:null==(f=e.accessibility)?void 0:null==(h=f.accessibilityData)?void 0:h.label)?l:c;a.update({mainText:c,subtitleText:d,label:b});g.ro(a.element,"ytp-offline-slate-single-text-line",!d);g.ro(a.B,"ytp-offline-slate-bar-hidden",!c&&!d)}},D6=function(a,b){var c=(0,g.Q)();
this.module="heartbeat";this.trigger=a;this.j=b;this.B=c},uab=function(a){g.UP.call(this,a);
var b=this;this.J=!1;this.T=0;this.D=!1;this.u=new g.fo(function(){var e=b.player.V(),f=b.getVideoData();E6(b)&&(nab(b)?oab(b,e,f):(pab(b),qab(b,e,f)))},0);
this.j=this.heartbeatParams=null;this.C=!1;this.I=new g.Th(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.ea=new g.Jx(void 0);this.Z=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new bab).getTimezoneOffset();this.B=new g.gF(this);g.F(this,this.u);g.F(this,this.B);pab(this);rab(this);this.B.S(a,"heartbeatparams",this.BA);this.B.S(a,"presentingplayerstatechange",this.aW);this.B.S(a,"videoplayerreset",this.bW);this.B.S(a,g.rB("heartbeat"),this.onCueRangeEnter);this.C&&this.j&&
sab(this,this.j);var c=new g.pB(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.pB(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.ye([c,d]);tab(this)},tab=function(a){var b=a.getVideoData();
b.il&&(b=b.botguardData)&&g.rO(b,a.player.V())},pab=function(a){var b=a.getVideoData();
if(b.il&&(b=new g.uIa(b),g.iO.isInitialized()||3<=a.sequenceNumber)){var c=null;if(b.videoData.vj){var d=g.vIa(b);if(d){c={};var e={};d=d.split("&");d=g.t(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=vab[Number(e.r1c)]);c.challenge=b.videoData.vj}}a.attestationResponse=c||void 0}},nab=function(a){var b=a.getVideoData();
if(!g.oJ(a.getVideoData())||b.RO)return!1;if(b.useInnertubeDrmService()&&b.Z){a="playready"===b.Z.flavor&&b.N("html5_innertube_heartbeats_for_playready");var c="widevine"===b.Z.flavor&&b.N("html5_innertube_heartbeats_for_widevine");b=g.fG(b.Z)&&b.N("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},wab=function(a){if(nab(a))return!!a.heartbeatParams;
var b=a.getVideoData();return g.oJ(a.getVideoData())&&b.useInnertubeDrmService()&&!b.Xk&&!b.hG?!1:!!b.heartbeatToken},F6=function(a,b){if(!a.u.isActive()&&a.J){var c=a.getVideoData();
if(wab(a)||c.isLivePlayback){if(void 0===b)if(a.D)if(a.C)b=7500;else{var d;b=(null==(d=a.heartbeatParams)?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().IO||6E4}else b=1E3;a.u.start(b)}}},Aab=function(a,b,c){b.Im&&(c=g.ji(c,{internalipoverride:b.Im}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.xc&&(d.kpt=b.xc);c=g.ji(c,d);g.$u(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.u.isActive()&&E6(a)){a.I.reset();a.sequenceNumber++;e=e.responseText;var f=xab(e);if(f){a.player.Qa("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(yab))?"0"===h[1]?0:1:-1;zab(a,f,e,h)}},
onError:function(e){E6(a)&&G6(a,!0,"net-"+e.status)},
onTimeout:function(){E6(a)&&G6(a,!0,"timeout")},
withCredentials:!0})},oab=function(a,b,c){var d;
if(null!=(d=a.heartbeatParams)&&d.url){var e=g.ji(a.heartbeatParams.url,{request_id:g.ita()});c.Ka&&(e=g.ji(e,{vvt:c.Ka}),c.mdxEnvironment&&(e=g.ji(e,{mdx_environment:c.mdxEnvironment})));g.JH(b,c.oauthToken).then(function(f){f&&(e=g.ji(e,{access_token:f}));Aab(a,c,e)})}},E6=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.U(a.player.Eb(a.getPlayerType()),4)?!1:wab(a)||b.isLivePlayback?!0:(H6(a),!1)},qab=function(a,b,c){var d,e={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!=(d=a.oa)?d:c.heartbeatServerData};a.Z=a.attestationResponse;c.il&&(e.attestationResponse=a.Z);var f=g.tO(c),h;d=null!=(h=f.client)?h:{};d.utcOffsetMinutes=a.utcOffsetMinutes;e.context=f;e.cpn=c.clientPlaybackNonce;if(h="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)d.timeZone=h;h={heartbeatChecks:[]};if(d=c.getPlayerResponse())c.heartbeatToken&&(e.heartbeatToken=c.heartbeatToken),(d=d.playabilityStatus)&&
(d=d.liveStreamability)&&d.liveStreamabilityRenderer&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.CH(b)){h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");f=Bab(a);d={};null!==f&&(d.clientPlayerPositionUtcMillis=f);var l,m;f=(null==(m=null==(l=a.player.vb())?void 0:g.jQ(l))?void 0:m.freePreviewWatchedDuration)||0;0<f&&(d.freePreviewWatchedDuration={seconds:""+f});h.unpluggedParams=d}e.heartbeatRequestParams=
h;c.isLivePlayback&&(l=Bab(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={utcTimeMillis:l}));a.player.ma("heartbeatRequest",{request:e});var n={timeout:3E4,onSuccess:function(p){if(!a.u.isActive()&&E6(a)){var q=a.getVideoData(),r=q.il&&null==a.Z,w;q.il=!(null==(w=p.heartbeatAttestationConfig)||!w.requiresAttestation)||r;r=p.playabilityStatus;w=JSON.stringify(r)||"{}";p.authenticationMismatch&&a.player.va("authshear",{});var y=-1;var z=p.playabilityStatus;z&&
(a.player.Qa("onHeartbeat",z),"OK"===z.status?y=p.stopHeartbeat?2:0:"UNPLAYABLE"===z.status?y=1:"LIVE_STREAM_OFFLINE"===z.status&&(y=0));a.sequenceNumber&&-1===y||a.I.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.oa=p.heartbeatServerData);p.playerCueRanges&&0<p.playerCueRanges.length&&(q.cueRanges=p.playerCueRanges,q.ma("dataupdated"));zab(a,r,w,y)}},
onError:function(p){E6(a)&&G6(a,!0,"net-"+p.status)},
onTimeout:function(){E6(a)&&G6(a,!0,"timeout")}};
g.JH(b,g.GJ(c)).then(function(p){p&&(n.eP="Bearer "+p);g.Kx(a.ea,"player/heartbeat",e,n)})},zab=function(a,b,c,d){-1===d?(b="decode "+g.Hf(c,3),G6(a,!1,b)):2===d?(H6(a),a.D=!0):(a.T=0,a.u.stop(),1===d?(a.D=!1,a.player.wg("heartbeat.stop",2,a.rf(c)),g.kw("heartbeatActionPlayerHalted",Cab(b))):(a.D=!0,c=0,a.C&&b&&(c=sab(a,b),a.player.ma("livestatedata",b)),c?F6(a,c):F6(a)))},sab=function(a,b){var c=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,d=!(!c||!(c.switchStreamsImmediately||
c.transitionTiming&&"STREAM_TRANSITION_TIMING_IMMEDIATELY"===c.transitionTiming)),e=Dab(c),f=a.getVideoData(),h=a.player.Eb(a.getPlayerType()),l=h.Rc()&&!g.uJ(f)&&!a.player.isAtLiveHead(a.getPlayerType());
if(f.V().C){var m,n=(null==(m=a.player.Zd())?void 0:m.Zb())||{};n.status=b.status||"";n.dvr=""+ +l;n["switch"]=""+ +d;n.ended=""+ +!(!c||!c.displayEndscreen);a.player.va("heartbeat",n)}if(l&&!d)return e;d=c&&c.streamTransitionEndpoint&&g.O(c.streamTransitionEndpoint,g.fI);if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(c&&c.transitionTiming))a.getVideoData().transitionEndpointAtEndOfStream=d;else{if(l=d)(l=d&&d.videoId)?(a.player.qm(l,{autonav:"1"},void 0,!0,!0,d,g.GJ(a.getVideoData())),a.ZD("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE",
"HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",b),l=!0):l=!1;if(l)return e}if("OK"===b.status.toUpperCase()){d=c&&c.broadcastId;l=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;m=d!==l&&null!=d;if(!f.hlsvp&&!f.yb||m){var p={video_id:f.videoId};f.XG&&(p.is_live_destination="1");a.player.N("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.watchNextResponse);
p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;p.force_gvi=f.Gm;p.Gk=f.Gk;f.J&&(p.vss_credentials_token=f.J,p.vss_credentials_token_type=f.pj);f.Ka&&(p.vvt=f.Ka);c=void 0;f.hlsvp||f.yb?m&&(c=new D6("broadcastIdChanged",l+","+d),a.ZD("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",b)):(d&&(c=new D6("formatsReceived",""+d)),a.ZD("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",b));a.player.loadVideoByPlayerVars(p,
void 0,void 0,void 0,c);return e}a.player.Pf("heartbeat",a.getPlayerType())}c&&c.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.I=!0,a.sb&&a.api.wx()):g.wL(h)&&(f=(null==(p=a.player.Zd())?void 0:p.Zb())||{},a.player.va("hbse",f,!0),a.player.wx(),a.player.Qa("onLiveMediaEnded",b)));return e},Dab=function(a){var b=0;
a&&a.pollDelayMs&&(a=Number(a.pollDelayMs))&&(b=a);return b},G6=function(a,b,c){var d=a.player.V();
if(!a.u.isActive()){a.u.stop();a.T++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.OO||b&&!g.oJ(a.getVideoData())&&!wab(a)&&f.isLivePlayback)f=!1;else{var h,l;(null==(l=a.heartbeatParams)?0:l.nx)?h=a.heartbeatParams.nx:h=f.MO||5;f=a.T>=h}f?(g.kw("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:Cab()),(b=a.getVideoData())&&b.isLivePlayback?a.player.wg(e,1,"Video playback interrupted. Please try again.",c):a.player.wg(e,1,"Sorry, there was an error licensing this video.",
c)):(d.N("html5_report_non_fatal_heartbeat_error")&&a.player.Hp(e,{msg:c}),F6(a,a.I.getValue()),g.Uh(a.I))}},Cab=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},H6=function(a){a.T=0;
a.u.stop();a.D=!1;a.sequenceNumber=0},rab=function(a){var b=a.getVideoData(),c=a.player.V();
if(b.isLivePlayback)if(g.qG(c.B)){a.C=!0;a.J=!0;if(!g.qH(c)||g.CH(c))a.offlineSlate=new lab(a.player),g.F(a,a.offlineSlate),g.kP(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;if("UNPLAYABLE"!==(null==(d=a.j)?void 0:d.status)||a.player.N("stop_heartbeat_on_unplayable_live_videos_killswitch"))a.j?(d=Dab(a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?F6(a,d):F6(a,7500):F6(a,1E3)}else a.player.wg("html5.unsupportedlive",
2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else g.pb(b.Ba,"heartbeat")&&a.player.Pf("heartbeat",a.getPlayerType())},Bab=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},xab=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},vab=["ATTESTATION_ERROR_UNKNOWN",
"ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],Eab={Goa:["BC","AD"],Foa:["Before Christ","Anno Domini"],iIa:"JFMAMJJASOND".split(""),UVa:"JFMAMJJASOND".split(""),VGa:"January February March April May June July August September October November December".split(" "),TVa:"January February March April May June July August September October November December".split(" "),kSa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WVa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),a5a:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),YVa:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),oTa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),XVa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),jIa:"SMTWTFS".split(""),VVa:"SMTWTFS".split(""),lSa:["Q1","Q2","Q3","Q4"],VPa:["1st quarter","2nd quarter","3rd quarter","4th quarter"],O$:["AM","PM"],wma:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],
RYa:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],xma:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],xV:6,b5a:[5,6],yV:5},Fab=Eab;Fab=Eab;g.k=bab.prototype;g.k.YP=Fab.xV;g.k.ZP=Fab.yV;g.k.clone=function(){var a=new bab(this.date);a.YP=this.YP;a.ZP=this.ZP;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.u||a.j){var b=this.getMonth()+a.j+12*a.u,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),z6(this,a.getDate()))};
g.k.equals=function(a){return!(!a||this.getYear()!=a.getYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};
g.k.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+Y$a(Math.abs(a),b?6:4),Y$a(this.getMonth()+1,2),Y$a(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var Gab=new g.fp("addUpcomingEventReminderEndpoint");var Hab=new g.fp("removeUpcomingEventReminderEndpoint");var Iab=new g.fp("updateUpcomingEventReminderButtonStateCommand");var eab=new g.fp("upcomingEventReminderButtonRenderer"),kab=new g.fp("upcomingEventReminderButtonStateRenderer");g.v(A6,g.mP);A6.prototype.hide=function(){this.buttonElement&&this.buttonElement.removeAttribute("aria-haspopup");g.mP.prototype.hide.call(this)};
A6.prototype.show=function(){this.buttonElement&&this.buttonElement.setAttribute("aria-haspopup","true");g.mP.prototype.show.call(this)};
A6.prototype.ra=function(){g.db(this.j);g.mP.prototype.ra.call(this)};g.v(B6,g.V);
B6.prototype.D=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.B(a.toggledServiceEndpoint):this.B(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;C6(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.sb)this.j.wb();else{var b=hab(this);b&&this.B(b.serviceEndpoint||b.command);b=(null==(a=g.O(null==b?void 0:b.command,g.sN))?void 0:a.commands)||[];a:{a=g.t(b);for(var c=a.next();!c.done;c=a.next()){var d=b=void 0;if(c=null==(b=g.O(c.value,
g.N3a))?void 0:null==(d=b.popup)?void 0:d.menuPopupRenderer){a=c;break a}}a=void 0}this.j||(this.j=new A6(this.G,this.buttonElement),this.j.Ca(this.element),g.F(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.B,this));b=this.j;b.menuPopupRenderer=a;dab(b)}};
B6.prototype.B=function(a){var b=g.O(a,Gab),c=g.O(a,Hab);if(a&&(b||c)){if(b){var d=b;var e="notification/add_upcoming_event_reminder"}else c&&(d=c,e="notification/remove_upcoming_event_reminder");if(e&&d&&d.params)for(jab(this,e,d.params),a=g.t(d.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&g.O(b,Iab)){this.u=g.O(b,Iab).state;C6(this);break}}};g.v(lab,g.V);g.k=lab.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.La=function(a){var b,c,d=null==a?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:c.offlineSlate;if(d){this.u=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.IU():mab(this,b);var e,f,h,l;if(c=null==a?void 0:null==(e=a.liveStreamability)?void 0:null==(f=e.liveStreamabilityRenderer)?void 0:null==(h=f.offlineSlate)?void 0:null==(l=h.liveStreamOfflineSlateRenderer)?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>
e&&(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new B6(this.api),this.j.Ca(this.Da("ytp-offline-slate-buttons")),g.F(this,this.j)),fab(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&fab(this.j,null,null);this.u=a}else this.u=null;this.MU()};
g.k.MU=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.Eb(),d=this.getVideoData();b=d.isLivePlayback&&(g.wL(c)||g.U(c,2)||g.U(c,64));var e=2===d.autonavState&&g.U(c,2);c=c.Rc()&&!g.uJ(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.u?this.sb?(null==a?0:g.IK(a,2))&&!this.getVideoData().jk&&(g.po(this.element,"ytp-offline-slate-collapsed"),this.C.stop(),g.po(this.B,"ytp-offline-slate-bar-fade"),this.D.start()):(this.show(),this.C.start(),this.api.ma("offlineslatestatechange"),
this.I&&this.api.wx()):this.sb&&(this.hide(),this.api.ma("offlineslatestatechange"))};
g.k.IU=function(){var a,b,c,d,e=null==(a=this.u)?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:null==(d=c.offlineSlate)?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.Ta()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(mab(this,e),this.countdownTimer.stop()):(mab(this,e,g.zN(b-a)),g.go(this.countdownTimer)))};
g.k.ra=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.V.prototype.ra.call(this)};D6.prototype.u=function(a){return this.trigger&&a.trigger?this.module===a.module&&this.trigger===a.trigger&&this.j===a.j:!1};
D6.prototype.isExpired=function(){return 6E4<(0,g.Q)()-this.B};
D6.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.v(uab,g.UP);g.k=uab.prototype;g.k.ra=function(){H6(this);this.player.Ef("heartbeat");g.UP.prototype.ra.call(this)};
g.k.onCueRangeEnter=function(){this.J=!0;F6(this,2E3)};
g.k.BA=function(a){this.heartbeatParams=a;F6(this,2E3)};
g.k.aW=function(a){var b;8===this.player.getPresentingPlayerType()||"UNPLAYABLE"===(null==(b=this.j)?void 0:b.status)&&!this.player.N("stop_heartbeat_on_unplayable_live_videos_killswitch")||(g.U(a.state,2)||g.U(a.state,64)?(H6(this),this.C&&(this.J=!0,F6(this,1E3))):(g.U(a.state,1)||g.U(a.state,8))&&F6(this,2E3))};
g.k.bW=function(){3!==this.player.getPresentingPlayerType()&&F6(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.Tj=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.ZD=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.kw("heartbeatActionPlayerTransitioned",a)};
g.k.rf=function(a){var b="LICENSE",c=xab(a);if(c)return c.reason||g.BQ[b]||"";(a=a.match(yab))&&(a=Number(a[1]))&&(b=g.eFa(a));return g.BQ[b]||""};
g.k.bA=function(){return!!this.offlineSlate&&this.offlineSlate.sb};
var yab=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.TP("heartbeat",uab);})(_yt_player);
